services:
  redis:
    image: redis:7-alpine
    container_name: baldia_mart_cache
    ports:
      - "6379:6379"
    networks:
      - baldia_net

  backend-api:
    build:
      context: ../backend-api
      dockerfile: ../docker/backend.Dockerfile
    container_name: baldia_mart_api
    ports:
      - "3000:3000"
    env_file:
      - ../backend-api/.env
    environment:
      - DB_HOST=host.docker.internal # Connect to Windows host PG 17
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
    depends_on:
      - redis
    networks:
      - baldia_net
    volumes:
      - ../backend-api/public/uploads:/app/public/uploads

  admin-panel:
    build:
      context: ../admin-panel
      dockerfile: ../docker/admin.Dockerfile
    container_name: baldia_mart_admin
    ports:
      - "3001:3000" # Maps Next.js to 3001
    environment:
      - NEXT_PUBLIC_API_URL=https://384b-175-107-236-228.ngrok-free.app/api/v1
    depends_on:
      - backend-api
    networks:
      - baldia_net

networks:
  baldia_net:
    driver: bridge
