import {
  Entity, PrimaryGeneratedColumn, Column, CreateDateColumn,
  Index, Unique,
} from 'typeorm';

/**
 * Daily Financial Snapshot — pre-computed daily aggregates for dashboards.
 *
 * Generated by a nightly cron job to avoid expensive real-time queries.
 * When wallet_id is NULL, it represents platform-wide totals.
 *
 * Used by:
 * - Admin: Platform P&L, revenue trends, COD reconciliation
 * - Vendor: Daily sales + commission breakdown
 * - Rider: Daily earnings + COD tracking
 */
@Index('IDX_SNAPSHOT_DATE', ['snapshotDate'])
@Index('IDX_SNAPSHOT_WALLET', ['walletId', 'snapshotDate'])
@Index('IDX_SNAPSHOT_USER_TYPE', ['userType', 'snapshotDate'])
@Unique('UQ_SNAPSHOT_DATE_WALLET', ['snapshotDate', 'walletId', 'userType'])
@Entity('daily_financial_snapshots')
export class DailyFinancialSnapshot {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'snapshot_date', type: 'date' })
  snapshotDate: Date;

  @Column({ name: 'wallet_id', type: 'uuid', nullable: true })
  walletId: string; // null = platform-wide aggregate

  @Column({
    name: 'user_type',
    type: 'enum',
    enum: ['Rider', 'Vendor', 'Platform'],
  })
  userType: string;

  @Column({ name: 'entity_name', nullable: true })
  entityName: string; // Rider name, Vendor name, etc. for display

  // ── Order Metrics ─────────────────────────────────────────────

  @Column({ name: 'total_orders', type: 'int', default: 0 })
  totalOrders: number;

  @Column({ name: 'completed_orders', type: 'int', default: 0 })
  completedOrders: number;

  @Column({ name: 'cancelled_orders', type: 'int', default: 0 })
  cancelledOrders: number;

  // ── Revenue Breakdown ─────────────────────────────────────────

  @Column('decimal', { name: 'gross_revenue', precision: 12, scale: 2, default: 0 })
  grossRevenue: number;

  @Column('decimal', { name: 'total_delivery_fees', precision: 12, scale: 2, default: 0 })
  totalDeliveryFees: number;

  @Column('decimal', { name: 'total_commissions', precision: 12, scale: 2, default: 0 })
  totalCommissions: number;

  @Column('decimal', { name: 'total_refunds', precision: 12, scale: 2, default: 0 })
  totalRefunds: number;

  @Column('decimal', { name: 'total_discounts', precision: 12, scale: 2, default: 0 })
  totalDiscounts: number;

  @Column('decimal', { name: 'total_bonuses', precision: 12, scale: 2, default: 0 })
  totalBonuses: number;

  @Column('decimal', { name: 'net_revenue', precision: 12, scale: 2, default: 0 })
  netRevenue: number;

  // ── Cash Flow ─────────────────────────────────────────────────

  @Column('decimal', { name: 'cod_collected', precision: 12, scale: 2, default: 0 })
  codCollected: number;

  @Column('decimal', { name: 'cod_remitted', precision: 12, scale: 2, default: 0 })
  codRemitted: number;

  @Column('decimal', { name: 'online_payments', precision: 12, scale: 2, default: 0 })
  onlinePayments: number;

  @Column('decimal', { name: 'total_payouts', precision: 12, scale: 2, default: 0 })
  totalPayouts: number;

  // ── Vertical Breakdown (Platform snapshots only) ──────────────

  @Column('decimal', { name: 'mart_revenue', precision: 12, scale: 2, default: 0 })
  martRevenue: number;

  @Column('decimal', { name: 'food_revenue', precision: 12, scale: 2, default: 0 })
  foodRevenue: number;

  @Column('decimal', { name: 'pharma_revenue', precision: 12, scale: 2, default: 0 })
  pharmaRevenue: number;

  @Column('decimal', { name: 'rashan_revenue', precision: 12, scale: 2, default: 0 })
  rashanRevenue: number;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;
}
